# Site settings
baseurl = "https://plasticuproject.github.io/blog/"
themesDir = "themes"
languageCode = "en-us"
title = "plasticuproject's blog"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-166142607-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "plasticuproject-github-io-blog"
paginate = 20

[author]
    name = "plasticuproject"

[params]
	name = "plasticuproject"
	description = "Self Promoting Blog"
	bio = ""
	# Enter optionally your twitter account
	twitter = ""
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = ""
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    cube     = "https://www.hackthebox.eu/profile/32882"
    twitter  = ""
    github   = "https://www.github.com/plasticuproject"
    envelope = "https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true)&input=Y0d4aGMzUnBZM1Z3Y205cVpXTjBRSEJ0TG0xbA"

