# Site settings
baseurl = "https://plasticuproject.com"
themesDir = "themes"
languageCode = "en-us"
title = "plasticuproject's blog"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
#googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "plasticuproject-github-io-blog"
paginate = 20

[author]
    name = "plasticuproject"

[params]
	name = "plasticuproject"
	description = "Self Promoting Blog"
	bio = "is my name and this is a blog."
	# Enter optionally your twitter account
	twitter = ""
	enableRSS = true

        # New G4 analytics tag
        GoogleAnalyticsID = "G-50Z66QSKH7"

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "Posts"
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = ""
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
        # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
        socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    terminal = "https://leetcode.com/plasticuproject"
    code     = "https://pypi.org/user/plasticuproject"
    cube     = "https://www.hackthebox.com/profile/32882"
    key      = "https://cryptohack.org/user/snuggles"
    github   = "https://www.github.com/plasticuproject"
    envelope = "mailto:plastic@plasticuproject.com"

